title: Planty
baseURL: /
params:
  favicon: images/favicon.png
  logo_dark: images/logo.svg
  logo_light: images/logo-white.svg
  hamburger_background_image: /images/leaf-light-grey.svg
  bg_image_primary: /images/header.jpg
  bg_image_primary_opacity: 60
  bg_image_secondary: /images/leaf-light-grey.svg
  bg_image_product: /images/leaf.svg
  snipcart_api_key: ''
  footer_text: >-
    کليه حقوق محصولات و محتوای اين سایت متعلق به گروه صنعتی هیراد ماشین می باشد
    و هر گونه کپی 

    برداری از محتوا و محصولات سایت غیر مجاز و بدون رضایت ماست
  palette: green
  main_menu:
    - title: محصولات
      url: /store
      style: link
    - title: درباره ما
      url: /about
      style: link
    - title: سوالات متداول
      url: /faq
      style: link
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
